AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Clinical backend serverless (Lambda + API Gateway + EventBridge + DynamoDB)

Globals:
  Function:
    Runtime: provided.al2023
    Architectures:
      - arm64
    Timeout: 30
    MemorySize: 512
    Environment:
      Variables:
        ENVIRONMENT: prod
        APPOINTMENT_TABLE: !Ref AppointmentsTable
        PATIENT_TABLE: !Ref PatientsTable
        CONSENT_TABLE: !Ref ConsentsTable
        ODONTOGRAM_TABLE: !Ref OdontogramsTable
        TREATMENT_PLAN_TABLE: !Ref TreatmentPlansTable
        USER_TABLE: !Ref UsersTable
        PLATFORM_ADMIN_EMAIL: mserranolm@gmail.com
        BOOTSTRAP_SECRET: ""
        SEND_SMS: "true"
        SEND_EMAIL: "true"
        USE_DYNAMODB: "true"
        CLINIC_TZ: America/Caracas
        SES_SENDER_EMAIL: no-reply@clinisense.aski-tech.net
        FRONTEND_BASE_URL: https://clinisense.aski-tech.net

Resources:

  # API Gateway REST API (para API Keys)
  ClinicalRestApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: !Sub "${AWS::StackName}-api"
      Description: Clinical REST API with API Key authentication
      StageName: prod
      EndpointConfiguration:
        Type: REGIONAL
      Cors:
        AllowOrigin: "'*'"
        AllowHeaders: "'Content-Type,Authorization,x-api-key'"
        AllowMethods: "'GET,POST,PUT,PATCH,DELETE,OPTIONS'"
      
  # API Key para autenticación del frontend
  ClinicalApiKey:
    Type: AWS::ApiGateway::ApiKey
    Properties:
      Name: !Sub "${AWS::StackName}-api-key"
      Description: API Key for Clinical frontend
      Enabled: true
      
  # Usage Plan con límite de llamadas diarias
  ClinicalUsagePlan:
    Type: AWS::ApiGateway::UsagePlan
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    DependsOn:
      - ClinicalRestApiprodStage
    Properties:
      UsagePlanName: !Sub "${AWS::StackName}-usage-plan"
      Description: Clinical API usage plan - 50000 requests per day
      ApiStages:
        - ApiId: !Ref ClinicalRestApi
          Stage: prod
      Throttle:
        RateLimit: 100
        BurstLimit: 500
      Quota:
        Limit: 50000
        Period: DAY
          
  # Asociar API Key con Usage Plan
  ClinicalUsagePlanKey:
    Type: AWS::ApiGateway::UsagePlanKey
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      KeyId: !Ref ClinicalApiKey
      KeyType: API_KEY
      UsagePlanId: !Ref ClinicalUsagePlan

  ClinicalApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: bootstrap
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref AppointmentsTable
        - DynamoDBCrudPolicy:
            TableName: !Ref PatientsTable
        - DynamoDBCrudPolicy:
            TableName: !Ref ConsentsTable
        - DynamoDBCrudPolicy:
            TableName: !Ref OdontogramsTable
        - DynamoDBCrudPolicy:
            TableName: !Ref TreatmentPlansTable
        - DynamoDBCrudPolicy:
            TableName: !Ref UsersTable
        - Statement:
          - Effect: Allow
            Action:
              - ses:SendEmail
              - ses:SendRawEmail
            Resource: arn:aws:ses:us-east-1:975738006503:identity/clinisense.aski-tech.net
        - Statement:
          - Effect: Allow
            Action:
              - dynamodb:CreateTable
              - dynamodb:DescribeTable
              - dynamodb:ListTables
              - dynamodb:TagResource
            Resource: !Sub "arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/*"
      Events:
        Api:
          Type: Api
          Properties:
            RestApiId: !Ref ClinicalRestApi
            Path: /{proxy+}
            Method: ANY
            Auth:
              ApiKeyRequired: true

  Reminder24hFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: bootstrap
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref AppointmentsTable
        - DynamoDBCrudPolicy:
            TableName: !Ref PatientsTable
        - DynamoDBCrudPolicy:
            TableName: !Ref ConsentsTable
        - Statement:
          - Effect: Allow
            Action:
              - ses:SendEmail
              - ses:SendRawEmail
            Resource: arn:aws:ses:us-east-1:975738006503:identity/clinisense.aski-tech.net
      Events:
        Every15Minutes:
          Type: Schedule
          Properties:
            Schedule: rate(15 minutes)
            Name: clinical-24h-reminder

  EndOfDayFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: bootstrap
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref AppointmentsTable
        - DynamoDBCrudPolicy:
            TableName: !Ref PatientsTable
        - DynamoDBCrudPolicy:
            TableName: !Ref ConsentsTable
        - Statement:
          - Effect: Allow
            Action:
              - ses:SendEmail
              - ses:SendRawEmail
            Resource: arn:aws:ses:us-east-1:975738006503:identity/clinisense.aski-tech.net
      Events:
        DailyClose:
          Type: Schedule
          Properties:
            Schedule: cron(0 22 * * ? *)
            Name: clinical-end-day-reminder


  AppointmentsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      BillingMode: PAY_PER_REQUEST
      TableName: clinical-appointments
      AttributeDefinitions:
        - AttributeName: PK
          AttributeType: S
        - AttributeName: SK
          AttributeType: S
      KeySchema:
        - AttributeName: PK
          KeyType: HASH
        - AttributeName: SK
          KeyType: RANGE

  PatientsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      BillingMode: PAY_PER_REQUEST
      TableName: clinical-patients
      AttributeDefinitions:
        - AttributeName: PK
          AttributeType: S
        - AttributeName: SK
          AttributeType: S
      KeySchema:
        - AttributeName: PK
          KeyType: HASH
        - AttributeName: SK
          KeyType: RANGE

  ConsentsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      BillingMode: PAY_PER_REQUEST
      TableName: clinical-consents
      AttributeDefinitions:
        - AttributeName: PK
          AttributeType: S
        - AttributeName: SK
          AttributeType: S
      KeySchema:
        - AttributeName: PK
          KeyType: HASH
        - AttributeName: SK
          KeyType: RANGE

  OdontogramsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      BillingMode: PAY_PER_REQUEST
      TableName: clinical-odontograms
      AttributeDefinitions:
        - AttributeName: PK
          AttributeType: S
        - AttributeName: SK
          AttributeType: S
      KeySchema:
        - AttributeName: PK
          KeyType: HASH
        - AttributeName: SK
          KeyType: RANGE

  TreatmentPlansTable:
    Type: AWS::DynamoDB::Table
    Properties:
      BillingMode: PAY_PER_REQUEST
      TableName: clinical-treatment-plans
      AttributeDefinitions:
        - AttributeName: PK
          AttributeType: S
        - AttributeName: SK
          AttributeType: S
      KeySchema:
        - AttributeName: PK
          KeyType: HASH
        - AttributeName: SK
          KeyType: RANGE

  UsersTable:
    Type: AWS::DynamoDB::Table
    Properties:
      BillingMode: PAY_PER_REQUEST
      TableName: clinical-users
      AttributeDefinitions:
        - AttributeName: PK
          AttributeType: S
        - AttributeName: SK
          AttributeType: S
      KeySchema:
        - AttributeName: PK
          KeyType: HASH
        - AttributeName: SK
          KeyType: RANGE


Outputs:
  ApiUrl:
    Description: REST API endpoint with API Key authentication
    Value: !Sub https://${ClinicalRestApi}.execute-api.${AWS::Region}.amazonaws.com/prod
    Export:
      Name: !Sub ${AWS::StackName}-ApiUrl
      
  ApiKey:
    Description: API Key for frontend authentication  
    Value: !Ref ClinicalApiKey
    Export:
      Name: !Sub ${AWS::StackName}-ApiKey
      
  ApiKeyId:
    Description: API Key ID for retrieving the actual key value
    Value: !Ref ClinicalApiKey
    Export:
      Name: !Sub ${AWS::StackName}-ApiKeyId
      
  UsagePlanId:
    Description: Usage Plan ID (100 requests per day)
    Value: !Ref ClinicalUsagePlan
    Export:
      Name: !Sub ${AWS::StackName}-UsagePlanId
